version: "3.8"
services:
  app:
    build: .
    image: my-node-app:latest
    env_file:
      - .env
    ports:
      - "${PORT}:3000"
    volumes:
      - ./:/app:cached
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PUBLIC_BACKEND_API_URL=${NEXT_PUBLIC_BACKEND_API_URL}
      - NEXT_PUBLIC_BACKEND_API_URLL=${NEXT_PUBLIC_BACKEND_API_URLL}
    command: npm run start
