version: "3.8"
services:
  app:
    build: .
    image: my-node-app:latest
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/app:cached
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start
