services:
  app:
    build:
      context: .
      args:
        - PORT=${PORT:-3000}
    image: nextjs-app:prod
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PUBLIC_BACKEND_API_URL=${NEXT_PUBLIC_BACKEND_API_URL}
      - NEXT_PUBLIC_BACKEND_API_URLL=${NEXT_PUBLIC_BACKEND_API_URLL}
